addReviewers: true
addAssignees: false
reviewers:
  - kyh0726
  - gomx3
  - Head-ddy
  - MlNTYS
  - lee0jae330
  - clue31415
  - fresh-woo
  - plamingo509
numberOfReviewers: 2
useReviewGroups: false
skipKeywords:
  - hotfix
