version: '3'
services:
  causw_database:
    image: postgres:9.3
    container_name: causw_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'causwlocaluser'
      POSTGRES_PASSWORD: 'causwlocalpw'
      POSTGRES_DB: 'causw'