version: '3'
services:
  causw_database:
    image: postgres:9.3
    container_name: causw_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'causwlocaluser'
      POSTGRES_PASSWORD: 'causwlocalpw'
      POSTGRES_DB: 'causw'
  causw_test_database:
    image: postgres:9.3
    container_name: causw_test_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'causwtestuser'
      POSTGRES_PASSWORD: 'causwtestpw'
      POSTGRES_DB: 'causwtest'