spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PROD_CAUSW_DB_URL}
    username: ${PROD_CAUSW_DB_USERNAME}
    password: ${PROD_CAUSW_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jwt:
    secret: jwtsecretkey