CREATE TABLE tb_crawl_site_config (
    id VARCHAR(255) NOT NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    site_id VARCHAR(100) NOT NULL,
    target_board_id VARCHAR(255) NOT NULL,
    crawler_type VARCHAR(50) NOT NULL,
    list_url VARCHAR(1000) NOT NULL,
    base_url VARCHAR(1000) NOT NULL,
    request_headers TEXT NOT NULL,
    request_delay_ms BIGINT NOT NULL,
    timeout_ms BIGINT NOT NULL,
    max_retries INT NOT NULL,
    max_articles INT NOT NULL,
    pagination_type VARCHAR(30) NOT NULL,
    page_param VARCHAR(100) NULL,
    max_pages INT NOT NULL,
    article_row_selector VARCHAR(255) NOT NULL,
    article_link_selector VARCHAR(255) NOT NULL,
    article_category_selector VARCHAR(255) NOT NULL,
    title_selector VARCHAR(255) NOT NULL,
    body_selector VARCHAR(255) NOT NULL,
    date_selector VARCHAR(255) NOT NULL,
    author_selector VARCHAR(255) NOT NULL,
    representative_image_selector VARCHAR(255) NOT NULL,
    date_format VARCHAR(100) NOT NULL,
    next_page_selector VARCHAR(255) NULL,
    requires_js_rendering BOOLEAN NOT NULL DEFAULT FALSE,
    requires_login BOOLEAN NOT NULL DEFAULT FALSE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT uk_crawl_site_config_site_id UNIQUE (site_id),
    CONSTRAINT fk_crawl_site_config_target_board
        FOREIGN KEY (target_board_id) REFERENCES tb_board (id)
);
