INSERT INTO tb_crawl_site_config (
    id,
    created_at,
    updated_at,
    site_id,
    target_board_id,
    crawler_type,
    list_url,
    base_url,
    request_headers,
    request_delay_ms,
    timeout_ms,
    max_retries,
    max_articles,
    pagination_type,
    page_param,
    max_pages,
    article_row_selector,
    article_link_selector,
    article_category_selector,
    title_selector,
    body_selector,
    date_selector,
    author_selector,
    representative_image_selector,
    date_format,
    next_page_selector,
    requires_js_rendering,
    requires_login,
    is_enabled
) VALUES (
    'cau-sw-notice-site-config',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6),
    'cau-sw-notice',
    (SELECT id FROM tb_board WHERE name = '소프트웨어학부' LIMIT 1),
    'CAU_SW_NOTICE',
    'https://cse.cau.ac.kr/sub05/sub0501.php?offset=',
    'https://cse.cau.ac.kr',
    '{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}',
    2000,
    10000,
    3,
    30,
    'PAGE_NUMBER',
    'offset',
    30,
    'table.table-basic tbody tr',
    'td.aleft a',
    'td span.tag',
    'div.header > h3',
    'div.fr-view',
    'div.header > div > span:nth-of-type(1)',
    'div.header > div > span:nth-of-type(3)',
    'div.fr-view > p > img',
    'yyyy-MM-dd',
    NULL,
    FALSE,
    FALSE,
    TRUE
);
