name: CD - Develop

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  app-main-build:
    name: Build & Deploy app-main Module in Github Actions
    runs-on: ubuntu-22.04

    steps:
      # 작업 엑세스 가능하게 $GITHUB_WORKSPACE에서 저장소를 체크아웃
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: dev

      # JDK & Gradle 설정
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-jdk-gradle

      # env 파일 추가
      - name: Copy .env from secret
        env:
          ENV_CONTENT: ${{ secrets.ENV_DEV }}
        run: |
            cat <<EOF > .env
            $ENV_CONTENT
            EOF

      # Flyway 마이그레이션
      - name: Run Flyway repair and migration
        run: |
          ./gradlew :app-main:flywayRepair -Penv=dev || true
          ./gradlew :app-main:flywayMigrate -Penv=dev

      # Build -> jar 파일 생성
      - name: Build app-main module
        run: ./gradlew clean :app-main:bootJar -x test

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-main-artifact
          path: |
            app-main/build/libs/*.jar
            .env


  app-main-deploy:
    name: CD app-main Module with SSH
    needs: app-main-build
    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-main-artifact

      # app-main JAR, env 파일 EC2에 전송
      - name: SCP app-main JAR and .env to EC2
        if: github.actor != 'nektos/act'
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.EC2_KEY_DEV }}
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER_DEV }}
          source: "*.jar,.env"
          target: "/home/ubuntu/app/app-main"

      # Redis Server 구동
      - name: Start redis-server
        if: github.actor != 'nektos/act'
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_KEY_DEV }}
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER_DEV }}
          script: |
            sudo systemctl start redis-server

      # 기존 서버 종료 및 app-main JAR 실행
      - name: Deploy app-main
        if: github.actor != 'nektos/act'
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_KEY_DEV }}
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER_DEV }}
          script: |
            sudo fuser -k -n tcp 8080 || true
            sleep 15
            APP_MAIN_JAR=$(ls -t /home/ubuntu/app/app-main/*.jar | head -n 1)
            sudo mkdir -p /var/log/spring-boot/app-main
            sudo nohup java -DLOG_DIR=/var/log/spring-boot/app-main -jar "$APP_MAIN_JAR" 1>/dev/null 2>&1 &


  notify:
    name: Discord Notify
    needs: [ app-main-deploy ]
    runs-on: ubuntu-22.04
    if: always()

    steps:
      # 작업 엑세스 가능하게 $GITHUB_WORKSPACE에서 저장소를 체크아웃
      - name: Checkout branch
        uses: actions/checkout@v6
        with:
          ref: dev

      - name: Notify Success
        if: ${{ github.actor != 'nektos/act' && needs.app-main-deploy.result == 'success' }}
        uses: ./.github/actions/discord-notify
        with:
          status: success
          branch: ${{ github.ref_name }}
          sha: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_id: ${{ github.run_id }}
          webhook: ${{ secrets.DISCORD_DEPLOY_WEBHOOK_URL_DEV }}
          role_id: ${{ secrets.DISCORD_BACKEND_ROLE_ID }}

      - name: Notify Failure
        if: ${{ github.actor != 'nektos/act' && needs.app-main-deploy.result != 'success' }}
        uses: ./.github/actions/discord-notify
        with:
          status: failure
          branch: ${{ github.ref_name }}
          sha: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_id: ${{ github.run_id }}
          webhook: ${{ secrets.DISCORD_DEPLOY_WEBHOOK_URL_DEV }}
          role_id: ${{ secrets.DISCORD_BACKEND_ROLE_ID }}
