name: caucse-prod

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: caucse-s3-bucket-prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Start redis-server
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          key: ${{ secrets.EC2_KEY_PROD }}
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER_PROD }}
          command: sudo systemctl start redis-server

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run:
          aws deploy create-deployment
          --application-name caucse-codedeploy-prod
          --deployment-group-name codedeploy-group-prod
          --file-exists-behavior OVERWRITE
          --s3-location bucket=caucse-s3-bucket-prod,bundleType=zip,key=$GITHUB_SHA.zip
          --region ap-northeast-2
